### ISSUE TITLE
Suggest use shutil.get_terminal_size instead of stty size

### ISSUE THREAD

**Issue by 264768502** [Yinzo/reprint#1]

**Comment by Yinzo** [comment]
Thanks for your suggestion :D 
Is there any problem of using `stty size` ?
Because I had tried `shutil.get_terminal_size`, and found out that it may still return a normal int even the script was not executed in terminal

**Comment by 264768502** [comment]
Maybe let reprint support Windows

**Comment by Yinzo** [comment]
That indeed matter :O 
I haven't test it on Windows, and that should be done
I will work on it now

**Comment by Yinzo** [comment]
reprint should support Windows now :D
