### ISSUE TITLE
win10下cmd不能正常运行。cant work with win10 cmd.

### ISSUE THREAD

**Issue by chengtian5huang** [Yinzo/reprint#10]
![default](https://user-images.githubusercontent.com/34744187/36522909-fc3854d2-17d9-11e8-866f-ba87a9ebd831.PNG)
你在windows底下试过吗。。。

**Comment by Yinzo** [comment]
reprint currently not support Windows, refer to issue #3

**Comment by saravanabalagi** [comment]
+1, is fix available?

**Comment by chengtian5huang** [comment]
i dont know. @Yinzo maybe u have any clue to fix?

**Comment by Yinzo** [comment]
There is a fix in the #3 but needs a extra dependency.

**Comment by Tridro** [comment]
under window environment, it's not working properly, even the demo code

**Comment by Yinzo** [comment]
windows cmd support is now added. I will soon update the PyPI version to 0.6.
