### ISSUE TITLE
wired spacing after packed with pyinstaller

### ISSUE THREAD

**Issue by JiaPai12138** [Yinzo/reprint#15]
![image](https://user-images.githubusercontent.com/72233260/148666935-392e6a99-20b3-40b2-843f-fc59698c1c03.png)

**Comment by Yinzo** [comment]
please provide further infomation, I have tried on window 11 and windows terminal, demo works fine.

**Comment by JiaPai12138** [comment]
np. A simple way to fix my situation is to use os.system('')
