### ISSUE TITLE
Doesn't work properly on Ubuntu

### ISSUE THREAD

**Issue by rohanliston** [Yinzo/reprint#3]
Tried this on Ubuntu 16.04 x64 with Python 3.5.2 in both the default terminal and [Terminator](https://gnometerminator.blogspot.com.au/p/introduction.html) and the output doesn't always print over the top of itself, instead printing on new lines as with regular `print()`.

When I run the example from the README, none of the lines seem to reprint. I've also tried [this other example](http://stackoverflow.com/a/40531113) and only the `Total Progress` line stays in the same spot (the `Moving File` line always prints on a new line).

Not sure if it matters, but I'm using `zsh`. I tried both of the above on OSX using Terminal.app (also using `zsh`) and it worked fine.

**Comment by Yinzo** [comment]
Thank you for reporting! 
I will now try to reproduce this issue on Ubuntu 16.04

**Comment by Yinzo** [comment]
Sorry for that I didn't reproduce the issue you mentioned D:
I use docker to install a ubuntu16.04 and install a Python 3.5.2 and switch to zsh to run the reprint demo, but everything seems fine on me :O 
May I have some screenshots for that? That could help me find out what is happening :D 
Thank you again for reporting :D

**Comment by rohanliston** [comment]
This is what I'm seeing in Terminator with zsh:

![Screenshot 1](https://cloud.githubusercontent.com/assets/1980929/22763597/0954a066-eeba-11e6-8f0e-2498638a1c33.png)
![Screenshot 2](https://cloud.githubusercontent.com/assets/1980929/22763669/52f1df90-eeba-11e6-847d-4b2915707592.png)

I also switched to the standard Ubuntu terminal + bash and the same thing happens:

![image](https://cloud.githubusercontent.com/assets/1980929/22763745/a86d4342-eeba-11e6-9439-009c3f2634c8.png)

**Comment by rohanliston** [comment]
I also tested it outside of Unity (i.e. Ctrl+Alt+F1) and the same thing happens.

**Comment by Yinzo** [comment]
These screenshots help a lot!
hmm, reprint definitely not working :/
I will try to figure it out, that may take some time :O

**Comment by jindaxia** [comment]
windows7
python3.6 同样的问题

**Comment by Yinzo** [comment]
@jindaxia Thanks for reporting, may I ask for the version of your reprint? You can find that by using `pip show reprint` :D

**Comment by jindaxia** [comment]
```
Name: reprint
Version: 0.2.1
Summary: A simple module for Python2/3 to print and refresh multi line output contents in terminal
Home-page: https://github.com/Yinzo/reprint
Author: Yinzo
Author-email: oop995+pypi@gmail.com
License: Apache-2.0
Location: c:\python36\lib\site-packages
Requires: backports.shutil-get-terminal-size, six
```

**Comment by bobvdvelde** [comment]
Just as a bump, this issue seems to persist. It does not work in ipython nor the linux mint 18.

```bash
python -c "import reprint
import time
with reprint.reprint.output(output_type='dict', initial_len=3, interval=0) as output:
  for i in range(3):
    output['a'] = i
    output['b'] = i*2
    output['c'] = i*3
    time.sleep(1)
"
a: 0                                                                                                                              
a: 0                                                                                                                               
b: 0                                                                                                                               
a: 1                                                                                                                               
b: 0                                                                                                                               
a: 1                                                                                                                               
b: 2                                                                                                                               
a: 1                                                                                                                               
b: 2                                                                                                                               
a: 2                                                                                                                               
b: 2                                                                                                                               
a: 2                                                                                                                               
b: 4                                                                                                                               
a: 2                                                                                                                               
b: 4                                                                                                                               
a: 2                                                                                                                               
b: 4                                                                                                                               
c: 6       
```

With version 2.2.2 of the lib
```bash
pip show reprint
Name: reprint
Version: 0.2.2
Summary: A simple module for Python2/3 to print and refresh multi line output contents in terminal
Home-page: https://github.com/Yinzo/reprint
Author: Yinzo
Author-email: oop995+pypi@gmail.com
License: Apache-2.0
Location: /home/rnvdv/.conda/envs/scratch/lib/python3.5/site-packages
Requires: six, backports.shutil-get-terminal-size
```

**Comment by Yinzo** [comment]
Thanks you guys, I finally reproducted this bug in a virtual machine, which is led by the failure of going previous line by string `\r\b\r`.

A new version of reprint is coming soon.

**Comment by Yinzo** [comment]
reprint 0.3.0 now released. please let me know if there is any problem :D 

![2017-06-25 16 50 45](https://user-images.githubusercontent.com/7458082/27514758-7f0c6ca4-59c6-11e7-9217-e81e716b4c93.png)

**Comment by bobvdvelde** [comment]
Looks good!

It reproduces nicely on my machine.

Thank for the update.

**Comment by Wulfre** [comment]
Not working on Windows 10 using Cmder -- which is a wrapper for ConEmu. My case is probably a really niche one, but it is still a problem that you might want to know about. Python 3 if that makes any difference.

![Horse](https://i.imgur.com/aO4YWeT.png)

![Files](https://i.imgur.com/OoYP3UI.png)

EDIT:

It's actually worse on the regular Command Line for Windows 10.

![cmd](https://i.imgur.com/k4Aojt2.png)

EDIT 2:

I fixed the problem by changing the magic character to `\x1b[1A` and changing the origin position (line 162) to `print(magic_char * (max(last_output_lines, lines)), end="")`. The escape code will not work on windows without using colorama though, so that would become a dependency and would require the line `colorama.init()` to be somewhere in the code (I have it on line 121).

**Comment by Yinzo** [comment]
@Wulfre Nice! And your solution is really helpful! I may consider making a small patch for Windows users :D

**Comment by valvesss** [comment]
Living in covid-19 era and the fix in 2017 stills works, thanks @Wulfre !! Made my day (night)

**Comment by Yinzo** [comment]
windows cmd support is now added. I will soon update the PyPI version to 0.6.
