### ISSUE TITLE
Zero division error

### ISSUE THREAD

**Issue by cat40** [Yinzo/reprint#4]
When I run
```
with output(output_type='dict') as output_lines:
    output_lines['a'] = 'test'
```
I receive a zero division error with the following traceback:
```
Traceback (most recent call last):
  File "C:\***\testReprint.py", line 4, in <module>
    output_lines['a'] = 'test'
  File "C:\Python27\lib\site-packages\reprint\reprint.py", line 243, in __exit__
    self.refresh(forced=True)
  File "C:\Python27\lib\site-packages\reprint\reprint.py", line 230, in refresh
    print_multi_line(self.warped_obj, self.force_single_line)
  File "C:\Python27\lib\site-packages\reprint\reprint.py", line 134, in print_multi_line
    lines = lines_of_content(content, columns)
  File "C:\Python27\lib\site-packages\reprint\reprint.py", line 112, in lines_of_content
    result += ceil((line_width(_k) + line_width(_v) + 2) / width)
ZeroDivisionError: division by zero
```
This only happens when I run it from IDLE by pressing f5. get_terminal_size() seems to return 0s when run in the IDLE shell. Running from the python shell returns an actual value. 
 
I recommend either an assert statement to give at least a sensical error:
`assert all(get_terminal_size()), 'Reprint does not work in the IDLE terminal.'`
 
Or a redefinition of the function in cases where length and width are zero to return arbitrary values. 
```
if not all(get_terminal_size()):
    def get_terminal_size():
        return 80, 25 #windows terminal size, can be anything?
```

**Comment by Yinzo** [comment]
Thanks a lot! This is very helpful ;D

**Comment by Yinzo** [comment]
I think I fixed it :D 
When fail to get true terminal size, a wrong size will make the output look horrible, so I use the normal build-in print instead ;D
