### ISSUE TITLE
Allow for custom sort order with dict output_type

### ISSUE THREAD

**Issue by kirkhansen** [Yinzo/reprint#7]
I would like to pass my own custom function for sorting the dict when using the `output_type='dict'` option. Currently it sorts by the first character of each key which is fine for some cases, but not all. It would be nice if there was a parameter, say `sort_function` that I could pass in and replace the `lambda x : x[0]` function.

**Comment by Yinzo** [comment]
Nice suggestion, I will add that parameter these days :D

**Comment by Yinzo** [comment]
new parameter for `output` object is updated  
You can update `reprint` to 0.5.0 and use it :D
Check out the README or the `random_sort.py` demo

**Comment by kirkhansen** [comment]
Sweet, I'll check it out next Monday. Thanks!
