### ISSUE TITLE
Format dict key to print

### ISSUE THREAD

**Issue by JohnPlayerSpecial** [Yinzo/reprint#8]
I am using it to print this list:

1: Valtteri Bottas   1:53.581                                          
2: Kimi Räikkönen    1:53.596                                                
3: Max Verstappen    1:54.807                                                
4: Felipe Massa      1:55.591                                                
5: Daniel Ricciardo  1:55.626                                                
6: Sergio Perez      1:55.676                                                
7: Nico Hulkenberg   1:55.623                                                
8: Daniil Kvyat      1:56.183                                                
9: Carlos Sainz Jr.  1:56.151                                                
10: Lance Stroll      1:56.397                                               
11: Kevin Magnussen   1:56.808                                               
12: Esteban Ocon      1:57.530                                               
13: Romain Grosjean   1:57.588                                              
14: Fernando Alonso   1:57.852                                               
15: Jolyon Palmer     1:58.786                                              
16: Pascal Wehrlein   1:58.776                                               
17: Marcus Ericsson   1:58.702                                               
18: Stoffel Vandoorne 1:58.586                                               
19: Sebastian Vettel  2:02.790                                               
20: Lewis Hamilton    1:53.520

but when the position printed is 10 and beyond, it breaks the align with the timings.
How can this be fixed?

I would like to be able to print

01: Valtteri Bottas   1:53.581                                          
02: Kimi Räikkönen    1:53.596                                                
03: Max Verstappen    1:54.807                                                
04: Felipe Massa      1:55.591                                                
05: Daniel Ricciardo  1:55.626                                                
06: Sergio Perez      1:55.676                                                
07: Nico Hulkenberg   1:55.623                                                
08: Daniil Kvyat      1:56.183                                                
09: Carlos Sainz Jr.  1:56.151                                                
10: Lance Stroll      1:56.397                                               
11: Kevin Magnussen   1:56.808                                               
12: Esteban Ocon      1:57.530                                               
13: Romain Grosjean   1:57.588                                              
14: Fernando Alonso   1:57.852                                               
15: Jolyon Palmer     1:58.786                                              
16: Pascal Wehrlein   1:58.776                                               
17: Marcus Ericsson   1:58.702                                               
18: Stoffel Vandoorne 1:58.586                                               
19: Sebastian Vettel  2:02.790                                               
20: Lewis Hamilton    1:53.520

I added just now by hand a leading space to format the driver standings, while the timings are in correct alignement in my output, but here github is breaking the alignement :)

EDIT 1:
 I added a leading 0 because the space isn't shown :)
Great library, very useful

**Comment by Yinzo** [comment]
May a auto padding function for the `key` helps? Which may automatically pad the all the keys with spaces to help you keep the alignment.
It's easy to add that function into `reprint` package :)

**Comment by Yinzo** [comment]
Oh I think i didn't get your point just now, you mean the output sorted by the key as string but not digits.

In your case, you can use a custom `sort_key` function to make the output sorted properly. 
Here is a sample code
```python
# -*- coding: utf8 -*-
from reprint import output

with output(output_type="dict", interval=0, sort_key=lambda x: int(x[0])) as output:
	output['1'] = 'Valtteri Bottas 1:53.581'
	output['2'] = 'Kimi Räikkönen 1:53.596'
	output['10'] = 'asdKimi Räikkönen 1:53.596'
```
