### ISSUE TITLE
Nice Table Formatting broken when adding colored text

### ISSUE THREAD

**Issue by JohnPlayerSpecial** [Yinzo/reprint#9]
I am inserting in a dict this string

```
CSI="\x1B["
driverName = "Sebastian Vettel"
driverName = CSI + "31;40m" + driverName + CSI + "0m"

currentStanding[ driverPosition ] = driverName
```
and then using your method to print this dict
`with output(output_type="dict", initial_len=1, interval=200, ) as currentStanding:`

when I try to output raw string it is all nice, but when I add the escape sequence to print the colored name it prints two columns..
Thanks

**Comment by Yinzo** [comment]
I think is the escape sequence that influence the column width calculation, which cause the output refresh bug.
I will give it a try, not sure right now :/

**Comment by JohnPlayerSpecial** [comment]
kindly thanks for your reply and feedback .
you're a friend

Il 06 Feb 2018 2:22 PM, "Yinzo" <notifications@github.com> ha scritto:

**Comment by Yinzo** [comment]
`reprint` 0.5.1 has been released to PYPI, use `pip install -U reprint` to update the package.
It fix the problem that colored text breaks the text formatting.

Thank you for your report, feel free to let me know if there still have problems ;D
